### ISSUE TITLE
Dovecot auth userdb does not support sql driver

### ISSUE THREAD

**Issue by derdeagle** [amateo/puppet-dovecot#6]
For the Dovecot auth userdb setting the driver "sql" is not supported.
Is there a specific reason for that? The passdb setting supports the "sql" driver.

According to the [Dovecot wiki](https://wiki.dovecot.org/UserDatabase) it should be supported.

Error message

> Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Driver sql not supported at /path/modules/dovecot/manifests/auth.pp:132:11 on node xxx

Do you plan to add support of sql driver in the userdb setting in the next releases?

**Comment by amateo** [comment]
I have to check why is not supported. I think it could be just a wrong check. I'll fix it as soon as possible.

**Comment by amateo** [comment]
I think is should be fixed in the new 1.0.8 release.
