### ISSUE TITLE
Critical: Missing dependencies to puppetlabs/concat 

### ISSUE THREAD

**Issue by func0der** [amateo/puppet-dovecot#8]
You have a missing dependency in your metadata.json.

The module your are missing is `puppetlabs/concat`.
Without it, you get the following error:

==> default: Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'concat' at /tmp/vagrant-puppet/modules-4f17d51763000278acd787fc5c996809/dovecot/manifests/auth.pp:31:3 on node contrib-stretch.localdomain

This has to be in there from day one.
Please fix this asap.

**Comment by amateo** [comment]
I should be fixed in the last version I have just uploaded.

**Comment by func0der** [comment]
Great. Thanks :)
